## 1 - Exploring the Tensorflow Library

In [3]:
import math
import numpy as np
import h5py
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.python.framework import ops
from tf_utils import *

%matplotlib inline
np.random.seed(1)

/home/devendra/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters



$$loss = \mathcal{L}(\hat{y}, y) = (\hat y^{(i)} - y^{(i)})^2 \tag{1}$$

In [4]:
y_hat = tf.constant(36,name="y_hat")
y = tf.constant(39,name="y")
loss = tf.Variable((y-y_hat)**2,name="loss")

init = tf.global_variables_initializer()

with tf.Session() as session:
    session.run(init)
    print(session.run(loss))

9


In [5]:
#easy example
a = tf.constant(2)
b = tf.constant(10,name="b")
c = tf.multiply(a,b)
print(c)

Tensor("Mul:0", shape=(), dtype=int32)


In [6]:
#in order to do multiplication you have to create session
sess = tf.Session()
print(sess.run(c))

20


In [7]:
# Change value of x in the feed_dict
x = tf.placeholder(tf.int64 , name="x")
print(sess.run(2*x,feed_dict={x:3}))
sess.close()

6


### 1.1 - Linear function

$Y = WX + b$, where $W$ and $X$ are random matrices and b is a random vector.

W is of shape (4, 3), X is (3,1) and b is (4,1).
- tf.matmul(..., ...) to do a matrix multiplication
- tf.add(..., ...) to do an addition
- np.random.randn(...) to initialize randomly


In [8]:
def linear_function():
    np.random.seed(1)
    X = tf.constant(np.random.randn(3,1),name="X")
    W = tf.constant(np.random.randn(4,3),name="W")
    b = tf.constant(np.random.randn(4,1),name="b")
    Y = tf.add(tf.matmul(W,X),b)
    
    sess = tf.Session()
    result = sess.run(Y)
    sess.close()
    
    return result

In [9]:
print("result= "+str(linear_function()))

result= [[-2.15657382]
 [ 2.95891446]
 [-1.08926781]
 [-0.84538042]]



**Method 1:**
```python
sess = tf.Session()
# Run the variables initialization (if needed), run the operations
result = sess.run(..., feed_dict = {...})
sess.close() # Close the session
```
**Method 2:**
```python
with tf.Session() as sess: 
    # run the variables initialization (if needed), run the operations
    result = sess.run(..., feed_dict = {...})
    # This takes care of closing the session for you :)
```

### 1.2  - Computing the sigmoid

In [10]:
def sigmoid(z):
    x = tf.placeholder(tf.float32 , name="x")
    sigmoid = tf.sigmoid(x)
    
    with tf.Session() as sess:
        result = sess.run(sigmoid,feed_dict={x:z})
    
    return result

In [11]:
print("sigmoid(0) = " + str(sigmoid(0)))
print("sigmoid(12) = " + str(sigmoid(12)))

sigmoid(0) = 0.5
sigmoid(12) = 0.9999938


### 1.3 - Computing the Cost

$$ J = - \frac{1}{m}  \sum_{i = 1}^m  \large ( \small y^{(i)} \log a^{ [2] (i)} + (1-y^{(i)})\log (1-a^{ [2] (i)} )\large )\small\tag{2}$$



- `tf.nn.sigmoid_cross_entropy_with_logits(logits = ...,  labels = ...)`

Your code should input `z`, compute the sigmoid (to get `a`) and then compute the cross entropy cost $J$. All this can be done using one call to `tf.nn.sigmoid_cross_entropy_with_logits`, which computes

$$- \frac{1}{m}  \sum_{i = 1}^m  \large ( \small y^{(i)} \log \sigma(z^{[2](i)}) + (1-y^{(i)})\log (1-\sigma(z^{[2](i)})\large )\small\tag{2}$$



In [12]:
def cost(logits , labels):
    z = tf.placeholder(tf.float32 , name="z")
    y = tf.placeholder(tf.float32 , name="y")
    
    cost = tf.nn.sigmoid_cross_entropy_with_logits(logits=z , labels=y)
    
    sess = tf.Session()
    
    cost = sess.run(cost,feed_dict={z:logits , y:labels})
    sess.close()
    
    return cost

In [13]:
logits = sigmoid(np.array([0.2,0.4,0.7,0.9]))
cost = cost(logits, np.array([0,0,1,1]))
print("cost = "+str(cost))

cost = [1.0053872  1.0366409  0.4138543  0.39956614]


### 1.4 - Using One Hot encodings

<img src="images/onehot.png" style="width:600px;height:150px;">

- tf.one_hot(labels, depth, axis) 

depth is 4 as there are 4 classes
and as of now axis is 0

In [14]:
def one_hot_matrix(labels,C):
    
    C = tf.constant(C , name="C") # depth
    one_hot_matrix = tf.one_hot(labels , C , axis=0)
    
    sess = tf.Session()
    
    one_hot_matrix = sess.run(one_hot_matrix)
    sess.close()
    
    return one_hot_matrix

In [15]:
labels = np.array([1,2,3,0,2,1])
one_hot = one_hot_matrix(labels,C=4)
print("one_hot = "+str(one_hot))

one_hot = [[0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]]


### 1.5 - Initialize with zeros and ones


In [16]:
def ones(shape):
    ones = tf.ones(shape)
    
    sess = tf.Session()
    
    ones=sess.run(ones)
    sess.close()
    
    return ones

In [17]:
print("ones = " + str(ones([3])))

ones = [1. 1. 1.]
